/* =============================================================
   SAMSON — Banque de connaissances (mode « Culture & Matières »)
   Chaque question : id, domain, name (réponse), alias?, prompt (énoncé),
   hint? (indice bonus), emoji (icône), level (1..3), region?
   Contenu volontairement diversifié : tous les continents et tous les âges.
   ============================================================= */

const SAMSON_DOMAINS = [
  { id: "litterature",  label: "Littérature",   icon: "📖", color: "#8b5cf6", desc: "Auteurs, romans et extraits du monde entier." },
  { id: "histoire",     label: "Histoire",      icon: "🏛️", color: "#f59e0b", desc: "Grandes figures et événements de chaque continent." },
  { id: "philosophie",  label: "Philosophie",   icon: "🧠", color: "#6366f1", desc: "Penseurs et idées d'hier et d'aujourd'hui." },
  { id: "informatique", label: "Informatique",  icon: "💻", color: "#0ea5e9", desc: "Programmation, langages et pionniers du numérique." },
  { id: "economie",     label: "Économie",      icon: "💰", color: "#16a34a", desc: "Notions clés et grands économistes." },
  { id: "geographie",   label: "Géographie",    icon: "🌍", color: "#14b8a6", desc: "Pays, capitales, fleuves et reliefs du monde." },
  { id: "sciences",     label: "Sciences",      icon: "🔬", color: "#ec4899", desc: "Physique, biologie et grands savants." },
  { id: "arts",         label: "Arts & Musique", icon: "🎨", color: "#f97316", desc: "Peintres, compositeurs et musiciens." },
  { id: "enfants",      label: "Pour enfants",  icon: "🧒", color: "#eab308", desc: "Couleurs, chiffres, animaux : pour débuter en douceur." },
  { id: "mathematiques", label: "Mathématiques", icon: "🔢", color: "#3b82f6", desc: "Nombres, géométrie et grands mathématiciens." },
  { id: "sport",        label: "Sport",         icon: "⚽", color: "#ef4444", desc: "Champions et disciplines des cinq continents." },
  { id: "religions",    label: "Religions & cultures", icon: "🕊️", color: "#a855f7", desc: "Grandes traditions spirituelles du monde." },
  { id: "langues",      label: "Langues",       icon: "🗣️", color: "#06b6d4", desc: "Langues et mots du monde entier." },
  { id: "civisme",      label: "Civisme",       icon: "⚖️", color: "#64748b", desc: "Citoyenneté, institutions et vivre-ensemble." },
  { id: "astronomie",   label: "Astronomie",    icon: "🪐", color: "#4f46e5", desc: "Planètes, étoiles et exploration spatiale." },
  { id: "sante",        label: "Santé & Corps", icon: "🩺", color: "#e11d48", desc: "Le corps humain et la santé." },
  { id: "cuisine",      label: "Cuisine du monde", icon: "🍲", color: "#ea580c", desc: "Plats et saveurs des cinq continents." },
  { id: "inventions",   label: "Inventions",    icon: "💡", color: "#ca8a04", desc: "Grandes inventions et leurs inventeurs." },
  { id: "faune",        label: "Faune & Flore", icon: "🦒", color: "#15803d", desc: "Animaux et plantes du monde entier." },
  { id: "metiers",      label: "Métiers",       icon: "👷", color: "#0891b2", desc: "Les métiers et ce qu'ils font." }
];

const SAMSON_QUIZ = [
  /* ===================== LITTÉRATURE ===================== */
  { id: "lit_hugo", domain: "litterature", name: "Victor Hugo", alias: ["Hugo"], level: 1, region: "Europe", emoji: "📖",
    prompt: "Auteur français des « Misérables » et de « Notre-Dame de Paris ».", hint: "Ses initiales sont V. H." },
  { id: "lit_achebe", domain: "litterature", name: "Chinua Achebe", alias: ["Achebe"], level: 2, region: "Afrique", emoji: "📖",
    prompt: "Écrivain nigérian, auteur de « Le monde s'effondre » (1958).", hint: "Père de la littérature africaine moderne." },
  { id: "lit_adichie", domain: "litterature", name: "Adichie", alias: ["Chimamanda Adichie", "Ngozi Adichie"], level: 2, region: "Afrique", emoji: "📖",
    prompt: "Romancière nigériane d'« Americanah » : Chimamanda Ngozi ___.", hint: "Autrice de « Nous sommes tous des féministes »." },
  { id: "lit_camus", domain: "litterature", name: "Camus", alias: ["Albert Camus"], level: 2, region: "Afrique", emoji: "📖",
    prompt: "Auteur de « L'Étranger » et « La Peste », Nobel 1957 : Albert ___.", hint: "Né en Algérie française." },
  { id: "lit_ba", domain: "litterature", name: "Mariama Bâ", alias: ["Mariama Ba", "Ba"], level: 3, region: "Afrique", emoji: "✉️",
    prompt: "Autrice sénégalaise d'« Une si longue lettre ».", hint: "Pionnière de la littérature féminine africaine." },
  { id: "lit_mahfouz", domain: "litterature", name: "Mahfouz", alias: ["Naguib Mahfouz"], level: 3, region: "Afrique", emoji: "📖",
    prompt: "Écrivain égyptien, prix Nobel de littérature 1988 : Naguib ___.", hint: "Célèbre pour sa « Trilogie du Caire »." },
  { id: "lit_marquez", domain: "litterature", name: "Márquez", alias: ["Marquez", "Garcia Marquez"], level: 2, region: "Amérique", emoji: "📖",
    prompt: "Auteur colombien de « Cent ans de solitude » : Gabriel García ___.", hint: "Maître du réalisme magique." },
  { id: "lit_tagore", domain: "litterature", name: "Tagore", alias: ["Rabindranath Tagore"], level: 3, region: "Asie", emoji: "📖",
    prompt: "Poète indien, premier Nobel de littérature non européen (1913).", hint: "Auteur de l'hymne de l'Inde." },
  { id: "lit_murakami", domain: "litterature", name: "Murakami", alias: ["Haruki Murakami"], level: 3, region: "Asie", emoji: "📖",
    prompt: "Romancier japonais de « Kafka sur le rivage » et « 1Q84 ».", hint: "Prénom : Haruki." },
  { id: "lit_prince", domain: "litterature", name: "Le Petit Prince", alias: ["Petit Prince"], level: 1, region: "Europe", emoji: "🌟",
    prompt: "Conte de Saint-Exupéry : « L'essentiel est invisible pour les yeux ».", hint: "Un enfant venu d'une autre planète." },
  { id: "lit_quichotte", domain: "litterature", name: "Don Quichotte", alias: ["Don Quijote", "Quichotte"], level: 2, region: "Europe", emoji: "🐴",
    prompt: "Roman de Cervantès sur un chevalier qui combat des moulins à vent.", hint: "Accompagné de Sancho Panza." },
  { id: "lit_romeo", domain: "litterature", name: "Roméo et Juliette", alias: ["Romeo et Juliette"], level: 1, region: "Europe", emoji: "❤️",
    prompt: "Tragédie de Shakespeare sur deux amants de Vérone.", hint: "Deux familles ennemies." },

  /* ===================== HISTOIRE ===================== */
  { id: "his_mandela", domain: "histoire", name: "Mandela", alias: ["Nelson Mandela"], level: 1, region: "Afrique", emoji: "✊",
    prompt: "Premier président noir d'Afrique du Sud, élu en 1994.", hint: "Emprisonné 27 ans, Nobel de la paix." },
  { id: "his_soundiata", domain: "histoire", name: "Soundiata Keïta", alias: ["Soundiata", "Sundiata"], level: 3, region: "Afrique", emoji: "🦁",
    prompt: "Fondateur de l'empire du Mali au XIIIe siècle.", hint: "Surnommé le « roi lion »." },
  { id: "his_moussa", domain: "histoire", name: "Mansa Moussa", alias: ["Kankou Moussa", "Kankan Moussa"], level: 3, region: "Afrique", emoji: "👑",
    prompt: "Empereur du Mali réputé pour sa richesse et son pèlerinage à La Mecque.", hint: "Sans doute l'homme le plus riche de l'Histoire." },
  { id: "his_nkrumah", domain: "histoire", name: "Nkrumah", alias: ["Kwame Nkrumah"], level: 3, region: "Afrique", emoji: "🌍",
    prompt: "Premier président du Ghana indépendant (1957), figure du panafricanisme.", hint: "Prénom : Kwame." },
  { id: "his_gandhi", domain: "histoire", name: "Gandhi", alias: ["Mahatma Gandhi"], level: 1, region: "Asie", emoji: "🕊️",
    prompt: "Leader de l'indépendance de l'Inde par la non-violence.", hint: "Surnommé le Mahatma." },
  { id: "his_bolivar", domain: "histoire", name: "Bolívar", alias: ["Bolivar", "Simon Bolivar"], level: 2, region: "Amérique", emoji: "⚔️",
    prompt: "« El Libertador » de plusieurs pays d'Amérique du Sud.", hint: "La Bolivie porte son nom." },
  { id: "his_toussaint", domain: "histoire", name: "Toussaint Louverture", alias: ["Louverture"], level: 3, region: "Amérique", emoji: "⛓️",
    prompt: "Figure de la révolution haïtienne contre l'esclavage.", hint: "Haïti, première république noire (1804)." },
  { id: "his_cleopatre", domain: "histoire", name: "Cléopâtre", alias: ["Cleopatre"], level: 1, region: "Afrique", emoji: "👑",
    prompt: "Dernière reine d'Égypte de la dynastie des Ptolémées.", hint: "Alliée de César puis de Marc Antoine." },
  { id: "his_cesar", domain: "histoire", name: "Jules César", alias: ["Cesar", "Jules Cesar"], level: 2, region: "Europe", emoji: "🏛️",
    prompt: "Général et homme d'État romain assassiné en -44.", hint: "« Le sort en est jeté »." },
  { id: "his_colomb", domain: "histoire", name: "Christophe Colomb", alias: ["Colomb"], level: 1, region: "Amérique", emoji: "⛵",
    prompt: "Navigateur qui atteint l'Amérique en 1492.", hint: "Il cherchait la route des Indes." },
  { id: "his_mao", domain: "histoire", name: "Mao Zedong", alias: ["Mao", "Mao Tse-toung"], level: 2, region: "Asie", emoji: "🏯",
    prompt: "Fondateur de la République populaire de Chine en 1949.", hint: "Le « Grand Timonier »." },

  /* ===================== PHILOSOPHIE ===================== */
  { id: "phi_socrate", domain: "philosophie", name: "Socrate", level: 1, region: "Europe", emoji: "🧠",
    prompt: "Philosophe grec : « Connais-toi toi-même ». Maître de Platon.", hint: "Condamné à boire la ciguë." },
  { id: "phi_platon", domain: "philosophie", name: "Platon", level: 2, region: "Europe", emoji: "🏛️",
    prompt: "Élève de Socrate, auteur de « La République » et de l'allégorie de la caverne.", hint: "Fondateur de l'Académie." },
  { id: "phi_descartes", domain: "philosophie", name: "Descartes", alias: ["Rene Descartes"], level: 2, region: "Europe", emoji: "🧠",
    prompt: "« Je pense, donc je suis ». Philosophe français du XVIIe siècle.", hint: "Auteur du « Discours de la méthode »." },
  { id: "phi_confucius", domain: "philosophie", name: "Confucius", level: 2, region: "Asie", emoji: "☯️",
    prompt: "Penseur chinois de la morale, de la famille et de l'harmonie sociale.", hint: "Ses « Entretiens » sont célèbres." },
  { id: "phi_kant", domain: "philosophie", name: "Kant", alias: ["Emmanuel Kant"], level: 3, region: "Europe", emoji: "🧠",
    prompt: "Philosophe allemand de la « Critique de la raison pure ».", hint: "Impératif catégorique." },
  { id: "phi_diop", domain: "philosophie", name: "Cheikh Anta Diop", alias: ["Anta Diop"], level: 3, region: "Afrique", emoji: "🌍",
    prompt: "Penseur et historien sénégalais de l'Afrique et de l'Égypte ancienne.", hint: "Une université de Dakar porte son nom." },
  { id: "phi_averroes", domain: "philosophie", name: "Averroès", alias: ["Averroes", "Ibn Rushd"], level: 3, region: "Afrique", emoji: "📜",
    prompt: "Philosophe et médecin andalou, grand commentateur d'Aristote.", hint: "Connu aussi sous le nom d'Ibn Rushd." },
  { id: "phi_aristote", domain: "philosophie", name: "Aristote", level: 2, region: "Europe", emoji: "🏛️",
    prompt: "Élève de Platon et précepteur d'Alexandre le Grand.", hint: "Fondateur de la logique." },

  /* ===================== INFORMATIQUE ===================== */
  { id: "inf_python", domain: "informatique", name: "Python", level: 1, emoji: "🐍",
    prompt: "Langage de programmation au nom de serpent, créé par Guido van Rossum.", hint: "Très utilisé en science des données." },
  { id: "inf_html", domain: "informatique", name: "HTML", level: 1, emoji: "🌐",
    prompt: "Langage de balisage qui structure les pages web.", hint: "HyperText Markup Language." },
  { id: "inf_linux", domain: "informatique", name: "Linux", level: 2, emoji: "🐧",
    prompt: "Système d'exploitation libre au logo de manchot, noyau de Linus Torvalds.", hint: "Sa mascotte s'appelle Tux." },
  { id: "inf_lovelace", domain: "informatique", name: "Ada Lovelace", alias: ["Lovelace"], level: 3, region: "Europe", emoji: "💻",
    prompt: "Considérée comme la première programmeuse de l'Histoire (XIXe siècle).", hint: "Elle travailla sur la machine de Babbage." },
  { id: "inf_turing", domain: "informatique", name: "Alan Turing", alias: ["Turing"], level: 2, region: "Europe", emoji: "💻",
    prompt: "Mathématicien britannique, père de l'informatique théorique.", hint: "Il déchiffra la machine Enigma." },
  { id: "inf_js", domain: "informatique", name: "JavaScript", level: 1, emoji: "🌐",
    prompt: "Langage qui rend les pages web interactives dans le navigateur.", hint: "À ne pas confondre avec Java." },
  { id: "inf_algo", domain: "informatique", name: "algorithme", level: 1, emoji: "⚙️",
    prompt: "Suite d'étapes précises pour résoudre un problème.", hint: "Le mot vient du savant Al-Khwârizmî." },
  { id: "inf_binaire", domain: "informatique", name: "binaire", level: 2, emoji: "🔢",
    prompt: "Système de numération à deux chiffres (0 et 1) utilisé par les ordinateurs.", hint: "Base 2." },
  { id: "inf_git", domain: "informatique", name: "Git", level: 2, emoji: "🌿",
    prompt: "Système de gestion de versions créé par Linus Torvalds.", hint: "GitHub est bâti autour de lui." },
  { id: "inf_bug", domain: "informatique", name: "bug", alias: ["bogue"], level: 1, emoji: "🐛",
    prompt: "Terme anglais désignant une erreur dans un programme.", hint: "On le « débogue »." },

  /* ===================== ÉCONOMIE ===================== */
  { id: "eco_inflation", domain: "economie", name: "inflation", level: 1, emoji: "📈",
    prompt: "Hausse générale et durable des prix.", hint: "L'argent perd de sa valeur." },
  { id: "eco_smith", domain: "economie", name: "Adam Smith", alias: ["Smith"], level: 3, region: "Europe", emoji: "💰",
    prompt: "Économiste écossais, auteur de « La Richesse des nations » (1776).", hint: "La « main invisible » du marché." },
  { id: "eco_pib", domain: "economie", name: "PIB", alias: ["produit interieur brut"], level: 2, emoji: "📊",
    prompt: "Indicateur mesurant la richesse produite par un pays en un an.", hint: "Produit Intérieur Brut." },
  { id: "eco_keynes", domain: "economie", name: "Keynes", alias: ["John Maynard Keynes"], level: 3, region: "Europe", emoji: "💰",
    prompt: "Économiste britannique prônant l'intervention de l'État pour relancer l'économie.", hint: "Le keynésianisme porte son nom." },
  { id: "eco_yunus", domain: "economie", name: "microcrédit", alias: ["microcredit"], level: 3, region: "Asie", emoji: "🤝",
    prompt: "Petit prêt popularisé par Muhammad Yunus au Bangladesh.", hint: "Il permet d'aider les plus pauvres à entreprendre." },
  { id: "eco_offre", domain: "economie", name: "offre et demande", alias: ["l'offre et la demande"], level: 2, emoji: "⚖️",
    prompt: "Les deux forces qui déterminent le prix sur un marché.", hint: "Quand l'une monte et l'autre baisse, le prix bouge." },
  { id: "eco_monnaie", domain: "economie", name: "monnaie", level: 1, emoji: "🪙",
    prompt: "Moyen d'échange accepté pour payer biens et services.", hint: "Euro, dollar, franc CFA…" },
  { id: "eco_troc", domain: "economie", name: "troc", level: 1, emoji: "🔄",
    prompt: "Échange d'un bien contre un autre, sans utiliser d'argent.", hint: "Ancêtre du commerce." },

  /* ===================== GÉOGRAPHIE ===================== */
  { id: "geo_caire", domain: "geographie", name: "Le Caire", alias: ["Caire"], level: 2, region: "Afrique", emoji: "🏙️",
    prompt: "Capitale de l'Égypte, traversée par le Nil.", hint: "Près des pyramides de Gizeh." },
  { id: "geo_nil", domain: "geographie", name: "Nil", level: 1, region: "Afrique", emoji: "🌊",
    prompt: "Grand fleuve d'Afrique, parmi les plus longs du monde.", hint: "Il se jette en Égypte." },
  { id: "geo_sahara", domain: "geographie", name: "Sahara", level: 1, region: "Afrique", emoji: "🏜️",
    prompt: "Plus grand désert chaud du monde, en Afrique du Nord.", hint: "Sable à perte de vue." },
  { id: "geo_everest", domain: "geographie", name: "Everest", level: 2, region: "Asie", emoji: "🏔️",
    prompt: "Plus haut sommet du monde, dans l'Himalaya.", hint: "Plus de 8 800 mètres." },
  { id: "geo_amazone", domain: "geographie", name: "Amazone", level: 2, region: "Amérique", emoji: "🌊",
    prompt: "Plus grand fleuve du monde par son débit, en Amérique du Sud.", hint: "Sa forêt est le « poumon vert »." },
  { id: "geo_tokyo", domain: "geographie", name: "Tokyo", level: 1, region: "Asie", emoji: "🏙️",
    prompt: "Capitale du Japon, l'une des plus peuplées du monde.", hint: "Sur l'île de Honshū." },
  { id: "geo_kilimandjaro", domain: "geographie", name: "Kilimandjaro", level: 3, region: "Afrique", emoji: "🏔️",
    prompt: "Plus haute montagne d'Afrique, en Tanzanie.", hint: "Un volcan coiffé de neige." },
  { id: "geo_lagos", domain: "geographie", name: "Lagos", level: 3, region: "Afrique", emoji: "🏙️",
    prompt: "Plus grande ville du Nigeria et l'une des plus grandes d'Afrique.", hint: "Métropole côtière très dynamique." },
  { id: "geo_andes", domain: "geographie", name: "Andes", level: 2, region: "Amérique", emoji: "⛰️",
    prompt: "Plus longue chaîne de montagnes du monde, en Amérique du Sud.", hint: "Elle traverse le Chili et le Pérou." },
  { id: "geo_australie", domain: "geographie", name: "Australie", level: 1, region: "Océanie", emoji: "🦘",
    prompt: "Pays-continent de l'hémisphère sud, capitale Canberra.", hint: "On y trouve le kangourou." },

  /* ===================== SCIENCES ===================== */
  { id: "sci_einstein", domain: "sciences", name: "Einstein", alias: ["Albert Einstein"], level: 1, region: "Europe", emoji: "🔬",
    prompt: "Physicien de la théorie de la relativité : E = mc².", hint: "Cheveux ébouriffés célèbres." },
  { id: "sci_gravite", domain: "sciences", name: "gravité", alias: ["gravite"], level: 1, emoji: "🍎",
    prompt: "Force qui attire les objets vers le sol.", hint: "La pomme de Newton." },
  { id: "sci_curie", domain: "sciences", name: "Marie Curie", alias: ["Curie"], level: 2, region: "Europe", emoji: "⚗️",
    prompt: "Deux fois prix Nobel, pionnière de l'étude de la radioactivité.", hint: "Première femme Nobel." },
  { id: "sci_photo", domain: "sciences", name: "photosynthèse", alias: ["photosynthese"], level: 2, emoji: "🌱",
    prompt: "Processus par lequel les plantes fabriquent leur énergie grâce à la lumière.", hint: "Elle produit de l'oxygène." },
  { id: "sci_adn", domain: "sciences", name: "ADN", level: 2, emoji: "🧬",
    prompt: "Molécule en double hélice qui porte l'information génétique.", hint: "Acide désoxyribonucléique." },
  { id: "sci_atome", domain: "sciences", name: "atome", level: 1, emoji: "⚛️",
    prompt: "Plus petite unité constituant la matière.", hint: "Noyau et électrons." },
  { id: "sci_newton", domain: "sciences", name: "Newton", alias: ["Isaac Newton"], level: 2, region: "Europe", emoji: "🍎",
    prompt: "Physicien de la loi de la gravitation universelle.", hint: "Une pomme serait tombée sur sa tête." },
  { id: "sci_volcan", domain: "sciences", name: "volcan", level: 1, emoji: "🌋",
    prompt: "Relief qui peut émettre de la lave en fusion.", hint: "Il entre en éruption." },

  /* ===================== ARTS & MUSIQUE ===================== */
  { id: "art_mozart", domain: "arts", name: "Mozart", level: 2, region: "Europe", emoji: "🎼",
    prompt: "Compositeur autrichien prodige du XVIIIe siècle.", hint: "« La Flûte enchantée »." },
  { id: "art_picasso", domain: "arts", name: "Picasso", level: 2, region: "Europe", emoji: "🎨",
    prompt: "Peintre espagnol, cofondateur du cubisme.", hint: "« Guernica »." },
  { id: "art_joconde", domain: "arts", name: "La Joconde", alias: ["Joconde", "Mona Lisa"], level: 1, region: "Europe", emoji: "🖼️",
    prompt: "Célèbre portrait au sourire mystérieux, peint par Léonard de Vinci.", hint: "Au musée du Louvre." },
  { id: "art_fela", domain: "arts", name: "Fela Kuti", alias: ["Fela"], level: 3, region: "Afrique", emoji: "🎷",
    prompt: "Musicien nigérian, pionnier de l'afrobeat.", hint: "Figure engagée de la musique africaine." },
  { id: "art_makeba", domain: "arts", name: "Miriam Makeba", alias: ["Makeba"], level: 3, region: "Afrique", emoji: "🎤",
    prompt: "Chanteuse sud-africaine surnommée « Mama Africa ».", hint: "Célèbre pour « Pata Pata »." },
  { id: "art_djembe", domain: "arts", name: "djembé", alias: ["djembe", "tam-tam"], level: 1, region: "Afrique", emoji: "🥁",
    prompt: "Instrument de percussion africain en bois et peau, joué avec les mains.", hint: "Originaire d'Afrique de l'Ouest." },

  /* ===================== POUR ENFANTS ===================== */
  { id: "kid_rouge", domain: "enfants", name: "rouge", level: 1, emoji: "🍓",
    prompt: "Couleur d'une fraise et d'une tomate bien mûre.", hint: "C'est aussi la couleur du cœur." },
  { id: "kid_trois", domain: "enfants", name: "trois", level: 1, emoji: "3️⃣",
    prompt: "Combien font 1 + 2 ? (en toutes lettres)", hint: "Le chiffre juste après 2." },
  { id: "kid_lion", domain: "enfants", name: "lion", level: 1, emoji: "🦁",
    prompt: "On l'appelle le roi des animaux, il rugit très fort.", hint: "Il a une grande crinière." },
  { id: "kid_lundi", domain: "enfants", name: "lundi", level: 1, emoji: "📅",
    prompt: "Le premier jour de la semaine.", hint: "Juste après dimanche." },
  { id: "kid_arc", domain: "enfants", name: "arc-en-ciel", level: 1, emoji: "🌈",
    prompt: "Il a sept couleurs et apparaît après la pluie.", hint: "On le voit quand il y a du soleil et de la pluie." },
  { id: "kid_abeille", domain: "enfants", name: "abeille", level: 1, emoji: "🐝",
    prompt: "Petit insecte jaune et noir qui fabrique du miel.", hint: "Elle butine les fleurs." },
  { id: "kid_dix", domain: "enfants", name: "dix", level: 1, emoji: "🖐️",
    prompt: "Le nombre de doigts sur nos deux mains. (en toutes lettres)", hint: "Cinq plus cinq." },
  { id: "kid_soleil", domain: "enfants", name: "soleil", level: 1, emoji: "☀️",
    prompt: "Cette étoile nous éclaire et nous réchauffe le jour.", hint: "Il se lève à l'est." },
  { id: "kid_chat", domain: "enfants", name: "chat", level: 1, emoji: "🐱",
    prompt: "Petit animal de compagnie qui miaule et aime chasser les souris.", hint: "Il fait « miaou »." },
  { id: "kid_bleu", domain: "enfants", name: "bleu", level: 1, emoji: "🔵",
    prompt: "Couleur du ciel par beau temps et de la mer.", hint: "Ni rouge ni vert." },
  { id: "kid_vache", domain: "enfants", name: "vache", level: 1, emoji: "🐄",
    prompt: "Animal de la ferme qui nous donne du lait.", hint: "Elle fait « meuh »." },
  { id: "kid_cinq", domain: "enfants", name: "cinq", level: 1, emoji: "🖐️",
    prompt: "Le nombre de doigts d'une seule main. (en toutes lettres)", hint: "Deux plus trois." },

  /* ===================== MATHÉMATIQUES ===================== */
  { id: "mat_pythagore", domain: "mathematiques", name: "Pythagore", level: 2, region: "Europe", emoji: "📐",
    prompt: "Mathématicien grec d'un célèbre théorème sur le triangle rectangle.", hint: "a² + b² = c²." },
  { id: "mat_khwarizmi", domain: "mathematiques", name: "Al-Khwârizmî", alias: ["Al-Khwarizmi", "Khwarizmi"], level: 3, region: "Asie", emoji: "🔢",
    prompt: "Savant du IXe siècle dont le nom a donné le mot « algorithme ».", hint: "Père de l'algèbre." },
  { id: "mat_pi", domain: "mathematiques", name: "pi", alias: ["nombre pi"], level: 1, emoji: "🥧",
    prompt: "Nombre valant environ 3,14, lié au cercle.", hint: "Périmètre = 2 × π × rayon." },
  { id: "mat_euclide", domain: "mathematiques", name: "Euclide", level: 3, region: "Europe", emoji: "📐",
    prompt: "Mathématicien grec surnommé le « père de la géométrie ».", hint: "Auteur des « Éléments »." },
  { id: "mat_addition", domain: "mathematiques", name: "addition", level: 1, emoji: "➕",
    prompt: "Opération qui consiste à ajouter des nombres.", hint: "2 + 3 = 5." },
  { id: "mat_triangle", domain: "mathematiques", name: "triangle", level: 1, emoji: "🔺",
    prompt: "Figure géométrique à trois côtés.", hint: "Il peut être équilatéral." },
  { id: "mat_thales", domain: "mathematiques", name: "Thalès", alias: ["Thales"], level: 2, region: "Europe", emoji: "📐",
    prompt: "Mathématicien grec d'un théorème sur les droites parallèles.", hint: "Souvent vu au collège." },
  { id: "mat_fraction", domain: "mathematiques", name: "fraction", level: 2, emoji: "➗",
    prompt: "Nombre écrit avec un numérateur sur un dénominateur.", hint: "Comme 1/2." },
  { id: "mat_zero", domain: "mathematiques", name: "zéro", alias: ["zero"], level: 1, region: "Asie", emoji: "0️⃣",
    prompt: "Chiffre notamment développé en Inde, qui représente « rien ».", hint: "Avant 1." },
  { id: "mat_johnson", domain: "mathematiques", name: "Katherine Johnson", alias: ["Johnson"], level: 3, region: "Amérique", emoji: "🚀",
    prompt: "Mathématicienne afro-américaine de la NASA, calculs des missions Apollo.", hint: "Film « Les Figures de l'ombre »." },

  /* ===================== SPORT ===================== */
  { id: "spo_pele", domain: "sport", name: "Pelé", alias: ["Pele"], level: 1, region: "Amérique", emoji: "⚽",
    prompt: "Footballeur brésilien triple champion du monde, surnommé « le Roi ».", hint: "Numéro 10 mythique." },
  { id: "spo_drogba", domain: "sport", name: "Drogba", alias: ["Didier Drogba"], level: 2, region: "Afrique", emoji: "⚽",
    prompt: "Footballeur ivoirien légendaire, artisan de la paix dans son pays.", hint: "Ancien buteur de Chelsea." },
  { id: "spo_bolt", domain: "sport", name: "Usain Bolt", alias: ["Bolt"], level: 1, region: "Amérique", emoji: "🏃",
    prompt: "Sprinteur jamaïcain, l'homme le plus rapide du monde.", hint: "Record sur 100 m." },
  { id: "spo_ali", domain: "sport", name: "Muhammad Ali", alias: ["Ali", "Cassius Clay"], level: 2, region: "Amérique", emoji: "🥊",
    prompt: "Boxeur américain surnommé « The Greatest ».", hint: "« Vole comme un papillon »." },
  { id: "spo_kipchoge", domain: "sport", name: "Kipchoge", alias: ["Eliud Kipchoge"], level: 3, region: "Afrique", emoji: "🏃",
    prompt: "Marathonien kényan, premier homme sous les 2 heures.", hint: "Prénom : Eliud." },
  { id: "spo_marathon", domain: "sport", name: "marathon", level: 2, region: "Europe", emoji: "🏅",
    prompt: "Course à pied de 42,195 km, inspirée d'une légende grecque.", hint: "Épreuve reine de l'athlétisme." },
  { id: "spo_cdm", domain: "sport", name: "Coupe du monde", alias: ["coupe du monde", "mondial"], level: 1, emoji: "🏆",
    prompt: "Compétition de football organisée tous les 4 ans.", hint: "La FIFA l'organise." },
  { id: "spo_judo", domain: "sport", name: "judo", level: 2, region: "Asie", emoji: "🥋",
    prompt: "Art martial japonais devenu sport olympique.", hint: "On porte un kimono blanc." },
  { id: "spo_basket", domain: "sport", name: "basket", alias: ["basketball", "basket-ball"], level: 1, region: "Amérique", emoji: "🏀",
    prompt: "Sport où l'on marque en mettant le ballon dans un panier.", hint: "La NBA en est la ligue phare." },
  { id: "spo_echecs", domain: "sport", name: "échecs", alias: ["echecs"], level: 2, emoji: "♟️",
    prompt: "Jeu de stratégie sur 64 cases avec rois, reines et cavaliers.", hint: "« Échec et mat »." },

  /* ===================== RELIGIONS & CULTURES ===================== */
  { id: "rel_islam", domain: "religions", name: "islam", level: 1, emoji: "☪️",
    prompt: "Religion dont le livre saint est le Coran.", hint: "Fidèles : les musulmans." },
  { id: "rel_christ", domain: "religions", name: "christianisme", level: 1, emoji: "✝️",
    prompt: "Religion fondée sur les enseignements de Jésus-Christ.", hint: "Livre : la Bible." },
  { id: "rel_boudd", domain: "religions", name: "bouddhisme", level: 2, region: "Asie", emoji: "☸️",
    prompt: "Voie spirituelle née en Inde, enseignée par le Bouddha.", hint: "Quête de l'éveil." },
  { id: "rel_hindou", domain: "religions", name: "hindouisme", level: 2, region: "Asie", emoji: "🕉️",
    prompt: "Grande religion de l'Inde, aux multiples divinités.", hint: "Le Gange y est sacré." },
  { id: "rel_juda", domain: "religions", name: "judaïsme", alias: ["judaisme"], level: 2, emoji: "✡️",
    prompt: "Religion monothéiste dont le livre est la Torah.", hint: "Fidèles : les juifs." },
  { id: "rel_mecque", domain: "religions", name: "La Mecque", alias: ["Mecque"], level: 2, region: "Asie", emoji: "🕋",
    prompt: "Ville sainte de l'islam, lieu du grand pèlerinage.", hint: "En Arabie saoudite." },
  { id: "rel_bouddha", domain: "religions", name: "Bouddha", level: 2, region: "Asie", emoji: "🧘",
    prompt: "Prince indien devenu « l'Éveillé », à l'origine du bouddhisme.", hint: "Nom : Siddhartha Gautama." },
  { id: "rel_ramadan", domain: "religions", name: "Ramadan", level: 1, emoji: "🌙",
    prompt: "Mois de jeûne observé par les musulmans.", hint: "On rompt le jeûne au coucher du soleil." },
  { id: "rel_jerusalem", domain: "religions", name: "Jérusalem", alias: ["Jerusalem"], level: 3, region: "Asie", emoji: "🕊️",
    prompt: "Ville sainte pour trois grandes religions monothéistes.", hint: "Au Proche-Orient." },
  { id: "rel_vaudou", domain: "religions", name: "vaudou", alias: ["vodou"], level: 3, region: "Afrique", emoji: "🌿",
    prompt: "Religion traditionnelle originaire d'Afrique de l'Ouest (Bénin).", hint: "Présente aussi en Haïti." },

  /* ===================== LANGUES ===================== */
  { id: "lan_mandarin", domain: "langues", name: "mandarin", level: 2, region: "Asie", emoji: "🗣️",
    prompt: "Langue la plus parlée au monde comme langue maternelle.", hint: "Parlée en Chine." },
  { id: "lan_swahili", domain: "langues", name: "swahili", level: 2, region: "Afrique", emoji: "🗣️",
    prompt: "Langue véhiculaire d'Afrique de l'Est (« jambo » = bonjour).", hint: "Parlée au Kenya, en Tanzanie." },
  { id: "lan_arabe", domain: "langues", name: "arabe", level: 1, emoji: "🗣️",
    prompt: "Langue qui s'écrit de droite à gauche, celle du Coran.", hint: "Parlée du Maghreb au Moyen-Orient." },
  { id: "lan_espagnol", domain: "langues", name: "espagnol", level: 1, region: "Amérique", emoji: "🗣️",
    prompt: "Langue de Cervantès, très parlée en Amérique latine.", hint: "« Hola ! »" },
  { id: "lan_alphabet", domain: "langues", name: "alphabet", level: 1, emoji: "🔤",
    prompt: "Ensemble ordonné des lettres d'une langue.", hint: "De A à Z." },
  { id: "lan_wolof", domain: "langues", name: "wolof", level: 2, region: "Afrique", emoji: "🗣️",
    prompt: "Langue largement parlée au Sénégal.", hint: "« Nangadef ? » = comment vas-tu ?" },
  { id: "lan_hindi", domain: "langues", name: "hindi", level: 2, region: "Asie", emoji: "🗣️",
    prompt: "L'une des principales langues officielles de l'Inde.", hint: "Écrit en devanagari." },
  { id: "lan_champollion", domain: "langues", name: "Champollion", level: 3, region: "Europe", emoji: "📜",
    prompt: "Il déchiffra les hiéroglyphes grâce à la pierre de Rosette.", hint: "Égyptologue français." },
  { id: "lan_verbe", domain: "langues", name: "verbe", level: 1, emoji: "🔤",
    prompt: "Mot qui exprime une action dans une phrase.", hint: "Manger, courir, jouer…" },
  { id: "lan_bonjour", domain: "langues", name: "bonjour", level: 1, emoji: "👋",
    prompt: "Mot français pour saluer quelqu'un dans la journée.", hint: "On le dit en arrivant." },

  /* ===================== CIVISME ===================== */
  { id: "civ_democratie", domain: "civisme", name: "démocratie", alias: ["democratie"], level: 2, emoji: "🗳️",
    prompt: "Régime où le peuple choisit ses dirigeants par le vote.", hint: "« Pouvoir du peuple »." },
  { id: "civ_vote", domain: "civisme", name: "vote", level: 1, emoji: "🗳️",
    prompt: "Acte par lequel un citoyen fait un choix lors d'une élection.", hint: "On le glisse dans l'urne." },
  { id: "civ_onu", domain: "civisme", name: "ONU", alias: ["nations unies", "organisation des nations unies"], level: 2, emoji: "🌐",
    prompt: "Organisation internationale pour la paix, fondée en 1945.", hint: "Siège à New York." },
  { id: "civ_drapeau", domain: "civisme", name: "drapeau", level: 1, emoji: "🚩",
    prompt: "Symbole en tissu qui représente un pays.", hint: "On le hisse sur un mât." },
  { id: "civ_constitution", domain: "civisme", name: "constitution", level: 3, emoji: "📜",
    prompt: "Texte fondamental qui organise les lois d'un pays.", hint: "La loi suprême." },
  { id: "civ_ua", domain: "civisme", name: "Union africaine", alias: ["union africaine"], level: 3, region: "Afrique", emoji: "🌍",
    prompt: "Organisation qui réunit les pays du continent africain.", hint: "Siège à Addis-Abeba." },
  { id: "civ_ecologie", domain: "civisme", name: "écologie", alias: ["ecologie"], level: 2, emoji: "♻️",
    prompt: "Protection de la nature et de l'environnement.", hint: "Contre la pollution." },
  { id: "civ_egalite", domain: "civisme", name: "égalité", alias: ["egalite"], level: 1, emoji: "⚖️",
    prompt: "Principe : les mêmes droits pour tous. Liberté, ___, fraternité.", hint: "Devise de la France." },
  { id: "civ_citoyen", domain: "civisme", name: "citoyen", level: 1, emoji: "🧑",
    prompt: "Personne membre d'un pays, avec des droits et des devoirs.", hint: "Il peut voter." },
  { id: "civ_recyclage", domain: "civisme", name: "recyclage", level: 1, emoji: "♻️",
    prompt: "Transformer les déchets pour les réutiliser.", hint: "On trie le verre et le papier." },

  /* ===================== ENRICHISSEMENTS (continents) ===================== */
  { id: "his_jeanne", domain: "histoire", name: "Jeanne d'Arc", alias: ["Jeanne d'Arc"], level: 2, region: "Europe", emoji: "⚔️",
    prompt: "Héroïne française du XVe siècle, brûlée à Rouen.", hint: "« La Pucelle d'Orléans »." },
  { id: "his_napoleon", domain: "histoire", name: "Napoléon", alias: ["Napoleon", "Napoleon Bonaparte"], level: 1, region: "Europe", emoji: "🎩",
    prompt: "Empereur français vaincu à Waterloo en 1815.", hint: "Petit chapeau célèbre." },
  { id: "his_gengis", domain: "histoire", name: "Gengis Khan", alias: ["Genghis Khan"], level: 2, region: "Asie", emoji: "🏹",
    prompt: "Fondateur du vaste empire mongol au XIIIe siècle.", hint: "Guerrier des steppes." },
  { id: "his_shaka", domain: "histoire", name: "Shaka Zulu", alias: ["Chaka", "Shaka"], level: 3, region: "Afrique", emoji: "🛡️",
    prompt: "Roi guerrier qui fonda la nation zouloue en Afrique australe.", hint: "Célèbre stratège du XIXe siècle." },
  { id: "lit_senghor", domain: "litterature", name: "Senghor", alias: ["Leopold Sedar Senghor", "Léopold Sédar Senghor"], level: 3, region: "Afrique", emoji: "📖",
    prompt: "Poète et premier président du Sénégal, chantre de la négritude.", hint: "Académicien français." },
  { id: "lit_soyinka", domain: "litterature", name: "Soyinka", alias: ["Wole Soyinka"], level: 3, region: "Afrique", emoji: "📖",
    prompt: "Dramaturge nigérian, premier Africain Nobel de littérature (1986).", hint: "Prénom : Wole." },
  { id: "lit_moliere", domain: "litterature", name: "Molière", alias: ["Moliere"], level: 1, region: "Europe", emoji: "🎭",
    prompt: "Dramaturge français de comédies comme « L'Avare » et « Le Malade imaginaire ».", hint: "La langue de ___." },
  { id: "lit_nuits", domain: "litterature", name: "Les Mille et Une Nuits", alias: ["Mille et Une Nuits", "mille et une nuits"], level: 2, region: "Asie", emoji: "🏮",
    prompt: "Recueil de contes arabes avec Shéhérazade, Aladdin et Sindbad.", hint: "Une reine raconte pour survivre." },
  { id: "phi_ubuntu", domain: "philosophie", name: "Ubuntu", level: 3, region: "Afrique", emoji: "🤝",
    prompt: "Philosophie africaine : « Je suis parce que nous sommes ».", hint: "Solidarité et humanité." },
  { id: "phi_beauvoir", domain: "philosophie", name: "Beauvoir", alias: ["Simone de Beauvoir"], level: 3, region: "Europe", emoji: "🧠",
    prompt: "Philosophe française, autrice du « Deuxième Sexe ».", hint: "« On ne naît pas femme, on le devient »." },
  { id: "sci_copernic", domain: "sciences", name: "Copernic", level: 3, region: "Europe", emoji: "🔭",
    prompt: "Il affirma que la Terre tourne autour du Soleil.", hint: "Modèle héliocentrique." },
  { id: "sci_cellule", domain: "sciences", name: "cellule", level: 2, emoji: "🔬",
    prompt: "Plus petite unité vivante d'un organisme.", hint: "On l'observe au microscope." },
  { id: "sci_electricite", domain: "sciences", name: "électricité", alias: ["electricite"], level: 1, emoji: "⚡",
    prompt: "Énergie qui fait fonctionner ampoules et appareils.", hint: "Elle passe dans les fils." },
  { id: "geo_gange", domain: "geographie", name: "Gange", level: 2, region: "Asie", emoji: "🌊",
    prompt: "Fleuve sacré qui traverse l'Inde.", hint: "Vénéré dans l'hindouisme." },
  { id: "geo_congo", domain: "geographie", name: "Congo", level: 2, region: "Afrique", emoji: "🌊",
    prompt: "Deuxième fleuve d'Afrique et l'un des plus profonds du monde.", hint: "Au cœur de l'Afrique centrale." },
  { id: "geo_mississippi", domain: "geographie", name: "Mississippi", level: 2, region: "Amérique", emoji: "🌊",
    prompt: "Grand fleuve des États-Unis.", hint: "Il traverse le pays du nord au sud." },
  { id: "art_ndour", domain: "arts", name: "Youssou N'Dour", alias: ["Youssou Ndour", "N'Dour"], level: 3, region: "Afrique", emoji: "🎤",
    prompt: "Star mondiale de la musique sénégalaise (mbalax).", hint: "Voix célèbre de « 7 Seconds »." },
  { id: "art_beethoven", domain: "arts", name: "Beethoven", level: 2, region: "Europe", emoji: "🎼",
    prompt: "Compositeur allemand devenu sourd, auteur de la « 9e Symphonie ».", hint: "« Hymne à la joie »." },
  { id: "art_kahlo", domain: "arts", name: "Frida Kahlo", alias: ["Kahlo"], level: 2, region: "Amérique", emoji: "🎨",
    prompt: "Peintre mexicaine célèbre pour ses autoportraits.", hint: "Sourcils reconnaissables." },
  { id: "eco_banque", domain: "economie", name: "banque", level: 1, emoji: "🏦",
    prompt: "Établissement qui garde l'argent et accorde des prêts.", hint: "On y ouvre un compte." },
  { id: "inf_internet", domain: "informatique", name: "internet", level: 1, emoji: "🌐",
    prompt: "Réseau mondial qui relie les ordinateurs entre eux.", hint: "On y « surfe »." },
  { id: "inf_ia", domain: "informatique", name: "intelligence artificielle", alias: ["IA"], level: 2, emoji: "🤖",
    prompt: "Domaine où des machines imitent le raisonnement humain.", hint: "Abrégée « IA »." },
  { id: "inf_souris", domain: "informatique", name: "souris", level: 1, emoji: "🖱️",
    prompt: "Objet qui déplace le curseur à l'écran.", hint: "On clique avec." },
  { id: "inf_clavier", domain: "informatique", name: "clavier", level: 1, emoji: "⌨️",
    prompt: "Objet couvert de touches pour taper du texte.", hint: "AZERTY ou QWERTY." },
  { id: "inf_mdp", domain: "informatique", name: "mot de passe", alias: ["motdepasse"], level: 1, emoji: "🔒",
    prompt: "Code secret qui protège un compte.", hint: "À garder pour soi." },

  /* ===================== ASTRONOMIE ===================== */
  { id: "ast_terre", domain: "astronomie", name: "Terre", level: 1, emoji: "🌍", prompt: "La planète bleue où nous vivons." },
  { id: "ast_mars", domain: "astronomie", name: "Mars", level: 1, emoji: "🔴", prompt: "La planète rouge, quatrième du système solaire." },
  { id: "ast_jupiter", domain: "astronomie", name: "Jupiter", level: 2, emoji: "🪐", prompt: "La plus grande planète du système solaire." },
  { id: "ast_saturne", domain: "astronomie", name: "Saturne", level: 2, emoji: "🪐", prompt: "Planète célèbre pour ses magnifiques anneaux." },
  { id: "ast_galaxie", domain: "astronomie", name: "galaxie", level: 2, emoji: "🌌", prompt: "Immense ensemble d'étoiles ; la nôtre est la Voie lactée." },
  { id: "ast_comete", domain: "astronomie", name: "comète", alias: ["comete"], level: 2, emoji: "☄️", prompt: "Astre glacé qui traîne une longue queue lumineuse." },
  { id: "ast_armstrong", domain: "astronomie", name: "Armstrong", alias: ["Neil Armstrong"], level: 2, region: "Amérique", emoji: "🌕", prompt: "Premier homme à marcher sur la Lune en 1969 : Neil ___." },
  { id: "ast_galilee", domain: "astronomie", name: "Galilée", alias: ["Galilee", "Galileo"], level: 3, region: "Europe", emoji: "🔭", prompt: "Astronome italien qui observa les lunes de Jupiter à la lunette." },
  { id: "ast_trounoir", domain: "astronomie", name: "trou noir", level: 3, emoji: "⚫", prompt: "Région de l'espace si dense que même la lumière n'en sort pas." },
  { id: "ast_satellite", domain: "astronomie", name: "satellite", level: 1, emoji: "🛰️", prompt: "Objet qui tourne autour d'une planète ; la Lune en est un." },

  /* ===================== SANTÉ & CORPS ===================== */
  { id: "san_coeur", domain: "sante", name: "cœur", alias: ["coeur"], level: 1, emoji: "❤️", prompt: "Organe qui pompe le sang dans tout le corps." },
  { id: "san_cerveau", domain: "sante", name: "cerveau", level: 1, emoji: "🧠", prompt: "Organe qui commande la pensée et les mouvements." },
  { id: "san_poumons", domain: "sante", name: "poumons", level: 1, emoji: "🫁", prompt: "Organes qui servent à respirer." },
  { id: "san_squelette", domain: "sante", name: "squelette", level: 2, emoji: "🦴", prompt: "Ensemble des os qui soutiennent le corps." },
  { id: "san_vitamine", domain: "sante", name: "vitamine", level: 2, emoji: "🍊", prompt: "Élément des aliments essentiel à la santé (C, D...)." },
  { id: "san_microbe", domain: "sante", name: "microbe", alias: ["bactérie", "bacterie"], level: 2, emoji: "🦠", prompt: "Être vivant minuscule qui peut causer des maladies." },
  { id: "san_pasteur", domain: "sante", name: "Pasteur", alias: ["Louis Pasteur"], level: 2, region: "Europe", emoji: "💉", prompt: "Savant français, inventeur du vaccin contre la rage." },
  { id: "san_vaccin", domain: "sante", name: "vaccin", level: 1, emoji: "💉", prompt: "Injection qui protège contre une maladie." },
  { id: "san_hygiene", domain: "sante", name: "hygiène", alias: ["hygiene"], level: 1, emoji: "🧼", prompt: "Se laver les mains en fait partie, pour rester en bonne santé." },
  { id: "san_imhotep", domain: "sante", name: "Imhotep", level: 3, region: "Afrique", emoji: "⚕️", prompt: "Sage de l'Égypte antique, considéré comme l'un des premiers médecins de l'Histoire." },

  /* ===================== CUISINE DU MONDE ===================== */
  { id: "cui_couscous", domain: "cuisine", name: "couscous", level: 1, region: "Afrique", emoji: "🍲", prompt: "Plat de semoule typique d'Afrique du Nord." },
  { id: "cui_thieb", domain: "cuisine", name: "thiéboudiène", alias: ["thieboudiene", "ceebu jen", "thiep"], level: 3, region: "Afrique", emoji: "🍚", prompt: "Plat national sénégalais : riz au poisson." },
  { id: "cui_sushi", domain: "cuisine", name: "sushi", level: 1, region: "Asie", emoji: "🍣", prompt: "Spécialité japonaise de riz et de poisson cru." },
  { id: "cui_tacos", domain: "cuisine", name: "tacos", level: 1, region: "Amérique", emoji: "🌮", prompt: "Spécialité mexicaine à base de tortilla garnie." },
  { id: "cui_pizza", domain: "cuisine", name: "pizza", level: 1, region: "Europe", emoji: "🍕", prompt: "Spécialité italienne ronde avec tomate et fromage." },
  { id: "cui_jollof", domain: "cuisine", name: "jollof", alias: ["jollof rice", "riz jollof"], level: 3, region: "Afrique", emoji: "🍚", prompt: "Riz épicé très populaire en Afrique de l'Ouest." },
  { id: "cui_injera", domain: "cuisine", name: "injera", level: 3, region: "Afrique", emoji: "🫓", prompt: "Galette éthiopienne légèrement acide qui sert d'assiette." },
  { id: "cui_curry", domain: "cuisine", name: "curry", level: 2, region: "Asie", emoji: "🍛", prompt: "Plat épicé originaire d'Inde." },
  { id: "cui_chocolat", domain: "cuisine", name: "chocolat", level: 1, region: "Amérique", emoji: "🍫", prompt: "Douceur faite à partir des fèves de cacao (origine amérindienne)." },
  { id: "cui_riz", domain: "cuisine", name: "riz", level: 1, region: "Asie", emoji: "🍚", prompt: "Céréale de base pour la moitié de l'humanité." },

  /* ===================== INVENTIONS & TECHNOLOGIE ===================== */
  { id: "inv_roue", domain: "inventions", name: "roue", level: 1, emoji: "⚙️", prompt: "Invention ronde essentielle pour rouler et transporter." },
  { id: "inv_imprimerie", domain: "inventions", name: "imprimerie", level: 2, region: "Europe", emoji: "🖨️", prompt: "Invention de Gutenberg pour reproduire les livres en série." },
  { id: "inv_telephone", domain: "inventions", name: "téléphone", alias: ["telephone"], level: 1, emoji: "📞", prompt: "Appareil de Graham Bell pour parler à distance." },
  { id: "inv_ampoule", domain: "inventions", name: "ampoule", level: 1, region: "Amérique", emoji: "💡", prompt: "Invention d'Edison qui éclaire nos maisons." },
  { id: "inv_avion", domain: "inventions", name: "avion", level: 1, region: "Amérique", emoji: "✈️", prompt: "Machine volante inventée par les frères Wright." },
  { id: "inv_boussole", domain: "inventions", name: "boussole", level: 2, region: "Asie", emoji: "🧭", prompt: "Instrument inventé en Chine pour trouver le nord." },
  { id: "inv_penicilline", domain: "inventions", name: "pénicilline", alias: ["penicilline"], level: 3, region: "Europe", emoji: "💊", prompt: "Premier antibiotique, découvert par Alexander Fleming." },
  { id: "inv_papier", domain: "inventions", name: "papier", level: 2, region: "Asie", emoji: "📄", prompt: "Support d'écriture inventé dans la Chine ancienne." },
  { id: "inv_automobile", domain: "inventions", name: "automobile", alias: ["voiture"], level: 2, region: "Europe", emoji: "🚗", prompt: "Véhicule à moteur ; Karl Benz en construisit l'un des premiers." },
  { id: "inv_vaccin", domain: "inventions", name: "vaccin", level: 2, region: "Europe", emoji: "💉", prompt: "Invention médicale de Jenner puis Pasteur qui protège des maladies." },

  /* ===================== FAUNE & FLORE ===================== */
  { id: "fau_elephant", domain: "faune", name: "éléphant", alias: ["elephant"], level: 1, region: "Afrique", emoji: "🐘", prompt: "Plus grand animal terrestre, avec une trompe." },
  { id: "fau_girafe", domain: "faune", name: "girafe", level: 1, region: "Afrique", emoji: "🦒", prompt: "Animal au très long cou, de la savane." },
  { id: "fau_baobab", domain: "faune", name: "baobab", level: 2, region: "Afrique", emoji: "🌳", prompt: "Arbre africain au tronc énorme, surnommé « arbre à l'envers »." },
  { id: "fau_kangourou", domain: "faune", name: "kangourou", level: 1, region: "Océanie", emoji: "🦘", prompt: "Animal australien qui saute et porte son petit dans une poche." },
  { id: "fau_panda", domain: "faune", name: "panda", level: 1, region: "Asie", emoji: "🐼", prompt: "Ours noir et blanc de Chine qui mange du bambou." },
  { id: "fau_requin", domain: "faune", name: "requin", level: 2, emoji: "🦈", prompt: "Grand poisson prédateur des mers." },
  { id: "fau_chameau", domain: "faune", name: "chameau", alias: ["dromadaire"], level: 2, region: "Afrique", emoji: "🐫", prompt: "Animal du désert avec une ou deux bosses." },
  { id: "fau_corail", domain: "faune", name: "corail", level: 3, region: "Océanie", emoji: "🪸", prompt: "Animal marin qui forme des récifs (la Grande Barrière en Australie)." },
  { id: "fau_manchot", domain: "faune", name: "manchot", alias: ["pingouin"], level: 2, emoji: "🐧", prompt: "Oiseau qui ne vole pas et vit surtout dans l'hémisphère sud." },
  { id: "fau_lion", domain: "faune", name: "lion", level: 1, region: "Afrique", emoji: "🦁", prompt: "Grand félin de la savane, « roi des animaux »." },

  /* ===================== MÉTIERS ===================== */
  { id: "met_medecin", domain: "metiers", name: "médecin", alias: ["medecin", "docteur"], level: 1, emoji: "🩺", prompt: "Il soigne les malades." },
  { id: "met_agriculteur", domain: "metiers", name: "agriculteur", alias: ["fermier", "paysan"], level: 1, emoji: "🌾", prompt: "Il cultive la terre et élève des animaux." },
  { id: "met_enseignant", domain: "metiers", name: "enseignant", alias: ["professeur", "instituteur"], level: 1, emoji: "👩‍🏫", prompt: "Il transmet le savoir aux élèves." },
  { id: "met_boulanger", domain: "metiers", name: "boulanger", level: 1, emoji: "🥖", prompt: "Il fabrique le pain." },
  { id: "met_pompier", domain: "metiers", name: "pompier", level: 1, emoji: "🚒", prompt: "Il éteint les incendies et porte secours." },
  { id: "met_pilote", domain: "metiers", name: "pilote", level: 2, emoji: "✈️", prompt: "Il conduit un avion." },
  { id: "met_architecte", domain: "metiers", name: "architecte", level: 2, emoji: "📐", prompt: "Il conçoit les plans des bâtiments." },
  { id: "met_infirmier", domain: "metiers", name: "infirmier", alias: ["infirmiere", "infirmière"], level: 1, emoji: "💉", prompt: "Il aide le médecin et prend soin des patients." },
  { id: "met_journaliste", domain: "metiers", name: "journaliste", level: 2, emoji: "📰", prompt: "Il informe le public dans les médias." },
  { id: "met_avocat", domain: "metiers", name: "avocat", level: 2, emoji: "⚖️", prompt: "Il défend les gens devant la justice." },

  /* ===================== ENRICHISSEMENTS (diversité des continents) ===================== */
  { id: "geo_dakar", domain: "geographie", name: "Dakar", level: 2, region: "Afrique", emoji: "🏙️", prompt: "Capitale du Sénégal, pointe la plus à l'ouest de l'Afrique continentale." },
  { id: "geo_pekin", domain: "geographie", name: "Pékin", alias: ["Beijing"], level: 2, region: "Asie", emoji: "🏯", prompt: "Capitale de la Chine." },
  { id: "geo_brasilia", domain: "geographie", name: "Brasília", alias: ["Brasilia"], level: 3, region: "Amérique", emoji: "🏙️", prompt: "Capitale du Brésil (ni Rio ni São Paulo)." },
  { id: "geo_nairobi", domain: "geographie", name: "Nairobi", level: 3, region: "Afrique", emoji: "🦁", prompt: "Capitale du Kenya." },
  { id: "geo_ottawa", domain: "geographie", name: "Ottawa", level: 3, region: "Amérique", emoji: "🍁", prompt: "Capitale du Canada (ni Toronto ni Montréal)." },
  { id: "his_toutankhamon", domain: "histoire", name: "Toutânkhamon", alias: ["Toutankhamon", "Tutankhamon"], level: 2, region: "Afrique", emoji: "⚱️", prompt: "Jeune pharaon égyptien dont le tombeau fut retrouvé intact." },
  { id: "his_selassie", domain: "histoire", name: "Haïlé Sélassié", alias: ["Haile Selassie", "Selassie"], level: 3, region: "Afrique", emoji: "👑", prompt: "Dernier empereur d'Éthiopie." },
  { id: "his_parks", domain: "histoire", name: "Rosa Parks", alias: ["Parks"], level: 2, region: "Amérique", emoji: "✊", prompt: "Femme noire américaine, symbole de la lutte contre la ségrégation (1955)." },
  { id: "his_suntzu", domain: "histoire", name: "Sun Tzu", alias: ["Sun Zi"], level: 3, region: "Asie", emoji: "⚔️", prompt: "Stratège chinois, auteur de « L'Art de la guerre »." },
  { id: "lit_neruda", domain: "litterature", name: "Neruda", alias: ["Pablo Neruda"], level: 3, region: "Amérique", emoji: "📖", prompt: "Poète chilien, prix Nobel de littérature 1971." },
  { id: "lit_frank", domain: "litterature", name: "Anne Frank", alias: ["Frank"], level: 2, region: "Europe", emoji: "📖", prompt: "Adolescente auteure d'un célèbre journal pendant la Seconde Guerre mondiale." },
  { id: "lit_pouchkine", domain: "litterature", name: "Pouchkine", alias: ["Pushkin"], level: 3, region: "Europe", emoji: "📖", prompt: "Grand poète national russe." },
  { id: "sci_mendeleiev", domain: "sciences", name: "Mendeleïev", alias: ["Mendeleiev"], level: 3, region: "Europe", emoji: "⚗️", prompt: "Chimiste russe, créateur du tableau périodique des éléments." },
  { id: "sci_darwin", domain: "sciences", name: "Darwin", alias: ["Charles Darwin"], level: 2, region: "Europe", emoji: "🐢", prompt: "Naturaliste anglais de la théorie de l'évolution." },
  { id: "sci_oxygene", domain: "sciences", name: "oxygène", alias: ["oxygene"], level: 1, emoji: "💨", prompt: "Gaz de l'air indispensable à la respiration." },
  { id: "spo_cricket", domain: "sport", name: "cricket", level: 2, region: "Asie", emoji: "🏏", prompt: "Sport de batte très populaire en Inde et au Pakistan." },
  { id: "spo_rugby", domain: "sport", name: "rugby", level: 2, region: "Océanie", emoji: "🏉", prompt: "Sport de ballon ovale, roi en Nouvelle-Zélande (les All Blacks)." },
  { id: "spo_senna", domain: "sport", name: "Senna", alias: ["Ayrton Senna"], level: 3, region: "Amérique", emoji: "🏎️", prompt: "Pilote de Formule 1 brésilien légendaire." },
  { id: "art_marley", domain: "arts", name: "Bob Marley", alias: ["Marley"], level: 2, region: "Amérique", emoji: "🎶", prompt: "Star jamaïcaine du reggae." },
  { id: "art_kidjo", domain: "arts", name: "Angélique Kidjo", alias: ["Kidjo"], level: 3, region: "Afrique", emoji: "🎤", prompt: "Chanteuse béninoise plusieurs fois récompensée aux Grammy Awards." },
  { id: "eco_impot", domain: "economie", name: "impôt", alias: ["impot", "taxe"], level: 2, emoji: "🧾", prompt: "Somme versée à l'État pour financer les services publics." },
  { id: "eco_bourse", domain: "economie", name: "bourse", level: 3, emoji: "📉", prompt: "Marché où s'échangent les actions des entreprises." },
  { id: "phi_hypatie", domain: "philosophie", name: "Hypatie", alias: ["Hypatia"], level: 3, region: "Afrique", emoji: "📜", prompt: "Femme philosophe et savante d'Alexandrie, en Égypte antique." },
  { id: "mat_carre", domain: "mathematiques", name: "carré", alias: ["carre"], level: 1, emoji: "⬜", prompt: "Figure à quatre côtés égaux et quatre angles droits." },
  { id: "mat_multi", domain: "mathematiques", name: "multiplication", level: 2, emoji: "✖️", prompt: "Opération notée × : 3 × 4 = 12." },
  { id: "lan_portugais", domain: "langues", name: "portugais", level: 1, region: "Amérique", emoji: "🗣️", prompt: "Langue parlée au Brésil et au Portugal." },
  { id: "lan_amharique", domain: "langues", name: "amharique", level: 3, region: "Afrique", emoji: "🗣️", prompt: "Langue officielle de l'Éthiopie." },
  { id: "civ_election", domain: "civisme", name: "élection", alias: ["election"], level: 1, emoji: "🗳️", prompt: "Moment où les citoyens votent pour choisir leurs représentants." },
  { id: "civ_solidarite", domain: "civisme", name: "solidarité", alias: ["solidarite"], level: 1, emoji: "🤝", prompt: "S'entraider entre citoyens." },
  { id: "rel_temple", domain: "religions", name: "temple", level: 1, emoji: "🛕", prompt: "Lieu de culte, notamment bouddhiste ou hindou." },
  { id: "rel_mosquee", domain: "religions", name: "mosquée", alias: ["mosquee"], level: 1, emoji: "🕌", prompt: "Lieu de prière des musulmans." },
  { id: "kid_vert", domain: "enfants", name: "vert", level: 1, emoji: "🟢", prompt: "Couleur de l'herbe et des feuilles des arbres." },
  { id: "kid_poule", domain: "enfants", name: "poule", level: 1, emoji: "🐔", prompt: "Animal de la ferme qui pond des œufs." },
  { id: "kid_quatre", domain: "enfants", name: "quatre", level: 1, emoji: "4️⃣", prompt: "Le nombre juste après trois. (en toutes lettres)" },
  { id: "kid_banane", domain: "enfants", name: "banane", level: 1, emoji: "🍌", prompt: "Fruit jaune tout courbé que le singe adore." }
];

if (typeof module !== "undefined") {
  module.exports = { SAMSON_DOMAINS, SAMSON_QUIZ };
}
