/* =============================================================
   SAMSON — Banque de connaissances (mode « Culture & Matières »)
   Chaque question : id, domain, name (réponse), alias?, prompt (énoncé),
   hint? (indice bonus), emoji (icône), level (1..3), region?
   Contenu volontairement diversifié : tous les continents et tous les âges.
   ============================================================= */

const SAMSON_DOMAINS = [
  { id: "litterature",  label: "Littérature",   icon: "📖", color: "#8b5cf6", desc: "Auteurs, romans et extraits du monde entier." },
  { id: "histoire",     label: "Histoire",      icon: "🏛️", color: "#f59e0b", desc: "Grandes figures et événements de chaque continent." },
  { id: "philosophie",  label: "Philosophie",   icon: "🧠", color: "#6366f1", desc: "Penseurs et idées d'hier et d'aujourd'hui." },
  { id: "informatique", label: "Informatique",  icon: "💻", color: "#0ea5e9", desc: "Programmation, langages et pionniers du numérique." },
  { id: "economie",     label: "Économie",      icon: "💰", color: "#16a34a", desc: "Notions clés et grands économistes." },
  { id: "geographie",   label: "Géographie",    icon: "🌍", color: "#14b8a6", desc: "Pays, capitales, fleuves et reliefs du monde." },
  { id: "sciences",     label: "Sciences",      icon: "🔬", color: "#ec4899", desc: "Physique, biologie et grands savants." },
  { id: "arts",         label: "Arts & Musique", icon: "🎨", color: "#f97316", desc: "Peintres, compositeurs et musiciens." },
  { id: "enfants",      label: "Pour enfants",  icon: "🧒", color: "#eab308", desc: "Couleurs, chiffres, animaux : pour débuter en douceur." }
];

const SAMSON_QUIZ = [
  /* ===================== LITTÉRATURE ===================== */
  { id: "lit_hugo", domain: "litterature", name: "Victor Hugo", alias: ["Hugo"], level: 1, region: "Europe", emoji: "📖",
    prompt: "Auteur français des « Misérables » et de « Notre-Dame de Paris ».", hint: "Ses initiales sont V. H." },
  { id: "lit_achebe", domain: "litterature", name: "Chinua Achebe", alias: ["Achebe"], level: 2, region: "Afrique", emoji: "📖",
    prompt: "Écrivain nigérian, auteur de « Le monde s'effondre » (1958).", hint: "Père de la littérature africaine moderne." },
  { id: "lit_adichie", domain: "litterature", name: "Adichie", alias: ["Chimamanda Adichie", "Ngozi Adichie"], level: 2, region: "Afrique", emoji: "📖",
    prompt: "Romancière nigériane d'« Americanah » : Chimamanda Ngozi ___.", hint: "Autrice de « Nous sommes tous des féministes »." },
  { id: "lit_camus", domain: "litterature", name: "Camus", alias: ["Albert Camus"], level: 2, region: "Afrique", emoji: "📖",
    prompt: "Auteur de « L'Étranger » et « La Peste », Nobel 1957 : Albert ___.", hint: "Né en Algérie française." },
  { id: "lit_ba", domain: "litterature", name: "Mariama Bâ", alias: ["Mariama Ba", "Ba"], level: 3, region: "Afrique", emoji: "✉️",
    prompt: "Autrice sénégalaise d'« Une si longue lettre ».", hint: "Pionnière de la littérature féminine africaine." },
  { id: "lit_mahfouz", domain: "litterature", name: "Mahfouz", alias: ["Naguib Mahfouz"], level: 3, region: "Afrique", emoji: "📖",
    prompt: "Écrivain égyptien, prix Nobel de littérature 1988 : Naguib ___.", hint: "Célèbre pour sa « Trilogie du Caire »." },
  { id: "lit_marquez", domain: "litterature", name: "Márquez", alias: ["Marquez", "Garcia Marquez"], level: 2, region: "Amérique", emoji: "📖",
    prompt: "Auteur colombien de « Cent ans de solitude » : Gabriel García ___.", hint: "Maître du réalisme magique." },
  { id: "lit_tagore", domain: "litterature", name: "Tagore", alias: ["Rabindranath Tagore"], level: 3, region: "Asie", emoji: "📖",
    prompt: "Poète indien, premier Nobel de littérature non européen (1913).", hint: "Auteur de l'hymne de l'Inde." },
  { id: "lit_murakami", domain: "litterature", name: "Murakami", alias: ["Haruki Murakami"], level: 3, region: "Asie", emoji: "📖",
    prompt: "Romancier japonais de « Kafka sur le rivage » et « 1Q84 ».", hint: "Prénom : Haruki." },
  { id: "lit_prince", domain: "litterature", name: "Le Petit Prince", alias: ["Petit Prince"], level: 1, region: "Europe", emoji: "🌟",
    prompt: "Conte de Saint-Exupéry : « L'essentiel est invisible pour les yeux ».", hint: "Un enfant venu d'une autre planète." },
  { id: "lit_quichotte", domain: "litterature", name: "Don Quichotte", alias: ["Don Quijote", "Quichotte"], level: 2, region: "Europe", emoji: "🐴",
    prompt: "Roman de Cervantès sur un chevalier qui combat des moulins à vent.", hint: "Accompagné de Sancho Panza." },
  { id: "lit_romeo", domain: "litterature", name: "Roméo et Juliette", alias: ["Romeo et Juliette"], level: 1, region: "Europe", emoji: "❤️",
    prompt: "Tragédie de Shakespeare sur deux amants de Vérone.", hint: "Deux familles ennemies." },

  /* ===================== HISTOIRE ===================== */
  { id: "his_mandela", domain: "histoire", name: "Mandela", alias: ["Nelson Mandela"], level: 1, region: "Afrique", emoji: "✊",
    prompt: "Premier président noir d'Afrique du Sud, élu en 1994.", hint: "Emprisonné 27 ans, Nobel de la paix." },
  { id: "his_soundiata", domain: "histoire", name: "Soundiata Keïta", alias: ["Soundiata", "Sundiata"], level: 3, region: "Afrique", emoji: "🦁",
    prompt: "Fondateur de l'empire du Mali au XIIIe siècle.", hint: "Surnommé le « roi lion »." },
  { id: "his_moussa", domain: "histoire", name: "Mansa Moussa", alias: ["Kankou Moussa", "Kankan Moussa"], level: 3, region: "Afrique", emoji: "👑",
    prompt: "Empereur du Mali réputé pour sa richesse et son pèlerinage à La Mecque.", hint: "Sans doute l'homme le plus riche de l'Histoire." },
  { id: "his_nkrumah", domain: "histoire", name: "Nkrumah", alias: ["Kwame Nkrumah"], level: 3, region: "Afrique", emoji: "🌍",
    prompt: "Premier président du Ghana indépendant (1957), figure du panafricanisme.", hint: "Prénom : Kwame." },
  { id: "his_gandhi", domain: "histoire", name: "Gandhi", alias: ["Mahatma Gandhi"], level: 1, region: "Asie", emoji: "🕊️",
    prompt: "Leader de l'indépendance de l'Inde par la non-violence.", hint: "Surnommé le Mahatma." },
  { id: "his_bolivar", domain: "histoire", name: "Bolívar", alias: ["Bolivar", "Simon Bolivar"], level: 2, region: "Amérique", emoji: "⚔️",
    prompt: "« El Libertador » de plusieurs pays d'Amérique du Sud.", hint: "La Bolivie porte son nom." },
  { id: "his_toussaint", domain: "histoire", name: "Toussaint Louverture", alias: ["Louverture"], level: 3, region: "Amérique", emoji: "⛓️",
    prompt: "Figure de la révolution haïtienne contre l'esclavage.", hint: "Haïti, première république noire (1804)." },
  { id: "his_cleopatre", domain: "histoire", name: "Cléopâtre", alias: ["Cleopatre"], level: 1, region: "Afrique", emoji: "👑",
    prompt: "Dernière reine d'Égypte de la dynastie des Ptolémées.", hint: "Alliée de César puis de Marc Antoine." },
  { id: "his_cesar", domain: "histoire", name: "Jules César", alias: ["Cesar", "Jules Cesar"], level: 2, region: "Europe", emoji: "🏛️",
    prompt: "Général et homme d'État romain assassiné en -44.", hint: "« Le sort en est jeté »." },
  { id: "his_colomb", domain: "histoire", name: "Christophe Colomb", alias: ["Colomb"], level: 1, region: "Amérique", emoji: "⛵",
    prompt: "Navigateur qui atteint l'Amérique en 1492.", hint: "Il cherchait la route des Indes." },
  { id: "his_mao", domain: "histoire", name: "Mao Zedong", alias: ["Mao", "Mao Tse-toung"], level: 2, region: "Asie", emoji: "🏯",
    prompt: "Fondateur de la République populaire de Chine en 1949.", hint: "Le « Grand Timonier »." },

  /* ===================== PHILOSOPHIE ===================== */
  { id: "phi_socrate", domain: "philosophie", name: "Socrate", level: 1, region: "Europe", emoji: "🧠",
    prompt: "Philosophe grec : « Connais-toi toi-même ». Maître de Platon.", hint: "Condamné à boire la ciguë." },
  { id: "phi_platon", domain: "philosophie", name: "Platon", level: 2, region: "Europe", emoji: "🏛️",
    prompt: "Élève de Socrate, auteur de « La République » et de l'allégorie de la caverne.", hint: "Fondateur de l'Académie." },
  { id: "phi_descartes", domain: "philosophie", name: "Descartes", alias: ["Rene Descartes"], level: 2, region: "Europe", emoji: "🧠",
    prompt: "« Je pense, donc je suis ». Philosophe français du XVIIe siècle.", hint: "Auteur du « Discours de la méthode »." },
  { id: "phi_confucius", domain: "philosophie", name: "Confucius", level: 2, region: "Asie", emoji: "☯️",
    prompt: "Penseur chinois de la morale, de la famille et de l'harmonie sociale.", hint: "Ses « Entretiens » sont célèbres." },
  { id: "phi_kant", domain: "philosophie", name: "Kant", alias: ["Emmanuel Kant"], level: 3, region: "Europe", emoji: "🧠",
    prompt: "Philosophe allemand de la « Critique de la raison pure ».", hint: "Impératif catégorique." },
  { id: "phi_diop", domain: "philosophie", name: "Cheikh Anta Diop", alias: ["Anta Diop"], level: 3, region: "Afrique", emoji: "🌍",
    prompt: "Penseur et historien sénégalais de l'Afrique et de l'Égypte ancienne.", hint: "Une université de Dakar porte son nom." },
  { id: "phi_averroes", domain: "philosophie", name: "Averroès", alias: ["Averroes", "Ibn Rushd"], level: 3, region: "Afrique", emoji: "📜",
    prompt: "Philosophe et médecin andalou, grand commentateur d'Aristote.", hint: "Connu aussi sous le nom d'Ibn Rushd." },
  { id: "phi_aristote", domain: "philosophie", name: "Aristote", level: 2, region: "Europe", emoji: "🏛️",
    prompt: "Élève de Platon et précepteur d'Alexandre le Grand.", hint: "Fondateur de la logique." },

  /* ===================== INFORMATIQUE ===================== */
  { id: "inf_python", domain: "informatique", name: "Python", level: 1, emoji: "🐍",
    prompt: "Langage de programmation au nom de serpent, créé par Guido van Rossum.", hint: "Très utilisé en science des données." },
  { id: "inf_html", domain: "informatique", name: "HTML", level: 1, emoji: "🌐",
    prompt: "Langage de balisage qui structure les pages web.", hint: "HyperText Markup Language." },
  { id: "inf_linux", domain: "informatique", name: "Linux", level: 2, emoji: "🐧",
    prompt: "Système d'exploitation libre au logo de manchot, noyau de Linus Torvalds.", hint: "Sa mascotte s'appelle Tux." },
  { id: "inf_lovelace", domain: "informatique", name: "Ada Lovelace", alias: ["Lovelace"], level: 3, region: "Europe", emoji: "💻",
    prompt: "Considérée comme la première programmeuse de l'Histoire (XIXe siècle).", hint: "Elle travailla sur la machine de Babbage." },
  { id: "inf_turing", domain: "informatique", name: "Alan Turing", alias: ["Turing"], level: 2, region: "Europe", emoji: "💻",
    prompt: "Mathématicien britannique, père de l'informatique théorique.", hint: "Il déchiffra la machine Enigma." },
  { id: "inf_js", domain: "informatique", name: "JavaScript", level: 1, emoji: "🌐",
    prompt: "Langage qui rend les pages web interactives dans le navigateur.", hint: "À ne pas confondre avec Java." },
  { id: "inf_algo", domain: "informatique", name: "algorithme", level: 1, emoji: "⚙️",
    prompt: "Suite d'étapes précises pour résoudre un problème.", hint: "Le mot vient du savant Al-Khwârizmî." },
  { id: "inf_binaire", domain: "informatique", name: "binaire", level: 2, emoji: "🔢",
    prompt: "Système de numération à deux chiffres (0 et 1) utilisé par les ordinateurs.", hint: "Base 2." },
  { id: "inf_git", domain: "informatique", name: "Git", level: 2, emoji: "🌿",
    prompt: "Système de gestion de versions créé par Linus Torvalds.", hint: "GitHub est bâti autour de lui." },
  { id: "inf_bug", domain: "informatique", name: "bug", alias: ["bogue"], level: 1, emoji: "🐛",
    prompt: "Terme anglais désignant une erreur dans un programme.", hint: "On le « débogue »." },

  /* ===================== ÉCONOMIE ===================== */
  { id: "eco_inflation", domain: "economie", name: "inflation", level: 1, emoji: "📈",
    prompt: "Hausse générale et durable des prix.", hint: "L'argent perd de sa valeur." },
  { id: "eco_smith", domain: "economie", name: "Adam Smith", alias: ["Smith"], level: 3, region: "Europe", emoji: "💰",
    prompt: "Économiste écossais, auteur de « La Richesse des nations » (1776).", hint: "La « main invisible » du marché." },
  { id: "eco_pib", domain: "economie", name: "PIB", alias: ["produit interieur brut"], level: 2, emoji: "📊",
    prompt: "Indicateur mesurant la richesse produite par un pays en un an.", hint: "Produit Intérieur Brut." },
  { id: "eco_keynes", domain: "economie", name: "Keynes", alias: ["John Maynard Keynes"], level: 3, region: "Europe", emoji: "💰",
    prompt: "Économiste britannique prônant l'intervention de l'État pour relancer l'économie.", hint: "Le keynésianisme porte son nom." },
  { id: "eco_yunus", domain: "economie", name: "microcrédit", alias: ["microcredit"], level: 3, region: "Asie", emoji: "🤝",
    prompt: "Petit prêt popularisé par Muhammad Yunus au Bangladesh.", hint: "Il permet d'aider les plus pauvres à entreprendre." },
  { id: "eco_offre", domain: "economie", name: "offre et demande", alias: ["l'offre et la demande"], level: 2, emoji: "⚖️",
    prompt: "Les deux forces qui déterminent le prix sur un marché.", hint: "Quand l'une monte et l'autre baisse, le prix bouge." },
  { id: "eco_monnaie", domain: "economie", name: "monnaie", level: 1, emoji: "🪙",
    prompt: "Moyen d'échange accepté pour payer biens et services.", hint: "Euro, dollar, franc CFA…" },
  { id: "eco_troc", domain: "economie", name: "troc", level: 1, emoji: "🔄",
    prompt: "Échange d'un bien contre un autre, sans utiliser d'argent.", hint: "Ancêtre du commerce." },

  /* ===================== GÉOGRAPHIE ===================== */
  { id: "geo_caire", domain: "geographie", name: "Le Caire", alias: ["Caire"], level: 2, region: "Afrique", emoji: "🏙️",
    prompt: "Capitale de l'Égypte, traversée par le Nil.", hint: "Près des pyramides de Gizeh." },
  { id: "geo_nil", domain: "geographie", name: "Nil", level: 1, region: "Afrique", emoji: "🌊",
    prompt: "Grand fleuve d'Afrique, parmi les plus longs du monde.", hint: "Il se jette en Égypte." },
  { id: "geo_sahara", domain: "geographie", name: "Sahara", level: 1, region: "Afrique", emoji: "🏜️",
    prompt: "Plus grand désert chaud du monde, en Afrique du Nord.", hint: "Sable à perte de vue." },
  { id: "geo_everest", domain: "geographie", name: "Everest", level: 2, region: "Asie", emoji: "🏔️",
    prompt: "Plus haut sommet du monde, dans l'Himalaya.", hint: "Plus de 8 800 mètres." },
  { id: "geo_amazone", domain: "geographie", name: "Amazone", level: 2, region: "Amérique", emoji: "🌊",
    prompt: "Plus grand fleuve du monde par son débit, en Amérique du Sud.", hint: "Sa forêt est le « poumon vert »." },
  { id: "geo_tokyo", domain: "geographie", name: "Tokyo", level: 1, region: "Asie", emoji: "🏙️",
    prompt: "Capitale du Japon, l'une des plus peuplées du monde.", hint: "Sur l'île de Honshū." },
  { id: "geo_kilimandjaro", domain: "geographie", name: "Kilimandjaro", level: 3, region: "Afrique", emoji: "🏔️",
    prompt: "Plus haute montagne d'Afrique, en Tanzanie.", hint: "Un volcan coiffé de neige." },
  { id: "geo_lagos", domain: "geographie", name: "Lagos", level: 3, region: "Afrique", emoji: "🏙️",
    prompt: "Plus grande ville du Nigeria et l'une des plus grandes d'Afrique.", hint: "Métropole côtière très dynamique." },
  { id: "geo_andes", domain: "geographie", name: "Andes", level: 2, region: "Amérique", emoji: "⛰️",
    prompt: "Plus longue chaîne de montagnes du monde, en Amérique du Sud.", hint: "Elle traverse le Chili et le Pérou." },
  { id: "geo_australie", domain: "geographie", name: "Australie", level: 1, region: "Océanie", emoji: "🦘",
    prompt: "Pays-continent de l'hémisphère sud, capitale Canberra.", hint: "On y trouve le kangourou." },

  /* ===================== SCIENCES ===================== */
  { id: "sci_einstein", domain: "sciences", name: "Einstein", alias: ["Albert Einstein"], level: 1, region: "Europe", emoji: "🔬",
    prompt: "Physicien de la théorie de la relativité : E = mc².", hint: "Cheveux ébouriffés célèbres." },
  { id: "sci_gravite", domain: "sciences", name: "gravité", alias: ["gravite"], level: 1, emoji: "🍎",
    prompt: "Force qui attire les objets vers le sol.", hint: "La pomme de Newton." },
  { id: "sci_curie", domain: "sciences", name: "Marie Curie", alias: ["Curie"], level: 2, region: "Europe", emoji: "⚗️",
    prompt: "Deux fois prix Nobel, pionnière de l'étude de la radioactivité.", hint: "Première femme Nobel." },
  { id: "sci_photo", domain: "sciences", name: "photosynthèse", alias: ["photosynthese"], level: 2, emoji: "🌱",
    prompt: "Processus par lequel les plantes fabriquent leur énergie grâce à la lumière.", hint: "Elle produit de l'oxygène." },
  { id: "sci_adn", domain: "sciences", name: "ADN", level: 2, emoji: "🧬",
    prompt: "Molécule en double hélice qui porte l'information génétique.", hint: "Acide désoxyribonucléique." },
  { id: "sci_atome", domain: "sciences", name: "atome", level: 1, emoji: "⚛️",
    prompt: "Plus petite unité constituant la matière.", hint: "Noyau et électrons." },
  { id: "sci_newton", domain: "sciences", name: "Newton", alias: ["Isaac Newton"], level: 2, region: "Europe", emoji: "🍎",
    prompt: "Physicien de la loi de la gravitation universelle.", hint: "Une pomme serait tombée sur sa tête." },
  { id: "sci_volcan", domain: "sciences", name: "volcan", level: 1, emoji: "🌋",
    prompt: "Relief qui peut émettre de la lave en fusion.", hint: "Il entre en éruption." },

  /* ===================== ARTS & MUSIQUE ===================== */
  { id: "art_mozart", domain: "arts", name: "Mozart", level: 2, region: "Europe", emoji: "🎼",
    prompt: "Compositeur autrichien prodige du XVIIIe siècle.", hint: "« La Flûte enchantée »." },
  { id: "art_picasso", domain: "arts", name: "Picasso", level: 2, region: "Europe", emoji: "🎨",
    prompt: "Peintre espagnol, cofondateur du cubisme.", hint: "« Guernica »." },
  { id: "art_joconde", domain: "arts", name: "La Joconde", alias: ["Joconde", "Mona Lisa"], level: 1, region: "Europe", emoji: "🖼️",
    prompt: "Célèbre portrait au sourire mystérieux, peint par Léonard de Vinci.", hint: "Au musée du Louvre." },
  { id: "art_fela", domain: "arts", name: "Fela Kuti", alias: ["Fela"], level: 3, region: "Afrique", emoji: "🎷",
    prompt: "Musicien nigérian, pionnier de l'afrobeat.", hint: "Figure engagée de la musique africaine." },
  { id: "art_makeba", domain: "arts", name: "Miriam Makeba", alias: ["Makeba"], level: 3, region: "Afrique", emoji: "🎤",
    prompt: "Chanteuse sud-africaine surnommée « Mama Africa ».", hint: "Célèbre pour « Pata Pata »." },
  { id: "art_djembe", domain: "arts", name: "djembé", alias: ["djembe", "tam-tam"], level: 1, region: "Afrique", emoji: "🥁",
    prompt: "Instrument de percussion africain en bois et peau, joué avec les mains.", hint: "Originaire d'Afrique de l'Ouest." },

  /* ===================== POUR ENFANTS ===================== */
  { id: "kid_rouge", domain: "enfants", name: "rouge", level: 1, emoji: "🍓",
    prompt: "Couleur d'une fraise et d'une tomate bien mûre.", hint: "C'est aussi la couleur du cœur." },
  { id: "kid_trois", domain: "enfants", name: "trois", level: 1, emoji: "3️⃣",
    prompt: "Combien font 1 + 2 ? (en toutes lettres)", hint: "Le chiffre juste après 2." },
  { id: "kid_lion", domain: "enfants", name: "lion", level: 1, emoji: "🦁",
    prompt: "On l'appelle le roi des animaux, il rugit très fort.", hint: "Il a une grande crinière." },
  { id: "kid_lundi", domain: "enfants", name: "lundi", level: 1, emoji: "📅",
    prompt: "Le premier jour de la semaine.", hint: "Juste après dimanche." },
  { id: "kid_arc", domain: "enfants", name: "arc-en-ciel", level: 1, emoji: "🌈",
    prompt: "Il a sept couleurs et apparaît après la pluie.", hint: "On le voit quand il y a du soleil et de la pluie." },
  { id: "kid_abeille", domain: "enfants", name: "abeille", level: 1, emoji: "🐝",
    prompt: "Petit insecte jaune et noir qui fabrique du miel.", hint: "Elle butine les fleurs." },
  { id: "kid_dix", domain: "enfants", name: "dix", level: 1, emoji: "🖐️",
    prompt: "Le nombre de doigts sur nos deux mains. (en toutes lettres)", hint: "Cinq plus cinq." },
  { id: "kid_soleil", domain: "enfants", name: "soleil", level: 1, emoji: "☀️",
    prompt: "Cette étoile nous éclaire et nous réchauffe le jour.", hint: "Il se lève à l'est." }
];

if (typeof module !== "undefined") {
  module.exports = { SAMSON_DOMAINS, SAMSON_QUIZ };
}
